```{r load data and variable yaml file}
#| echo: false
#| message: false

`%>%` <- magrittr::`%>%`
params <- yaml::read_yaml("_variables.yaml")
data <- readr::read_csv("data.csv", show_col_types = FALSE)

# params <- yaml::read_yaml("RED_15044/_variables.yaml")
# data <- readr::read_csv("RED_15044/data.csv", show_col_types = FALSE)

```


<!-- KU ADRC DS COHORT -->

```{r extract person information from kuadrc cohort used for other parts of the report}
#| echo: false
#| eval: !expr (any(params[grepl("kuadrc", names(params))] == TRUE))

intake <- BRIDGE21::get_database_values(
  subject_fname,
  subject_lname,
  subject_birthdate,
  date = NULL,
  data = data,
  event_name = redcap_event_name
)

intake <- intake[!duplicated(intake[2:4]), ]

intake$subject_birthdate <- as.Date(
  intake$subject_birthdate,
  tryFormats = c("%m/%d/%Y", "%m/%d/%y")
)

date <- c("visitmo", "visitday", "visityr")
date_expr <- rlang::expr(visitmo / visitday / visityr)

data$sex <- ifelse(is.na(data$sex), data$birthsex, data$sex)

data$frmdatea1 <- as.Date(data$frmdatea1, "%m/%d/%Y")

date_adjust <- !is.na(data$frmdatea1)
if (any(date_adjust)) {
  data$visityr[date_adjust] <- format(data$frmdatea1[date_adjust], "%Y")
  data$visitmo[date_adjust] <- format(data$frmdatea1[date_adjust], "%m")
  data$visitday[date_adjust] <- format(data$frmdatea1[date_adjust], "%d")
}

visit <- BRIDGE21::get_database_values(
  sex,
  final_impression,
  date = date,
  data = data,
  event_name = redcap_event_name
)

visit <- BRIDGE21::format_date(visit, !!date_expr)

visit$age_at_visit <-
  visit$Date %>%
  as.Date(format = "%m/%d/%Y") %>%
  {
    as.numeric((. - intake$subject_birthdate) / 365.25)
  } %>%
  floor()

```


```{r display person information in a table format for kuadrc cohort}
#| echo: false
#| eval: !expr params$kuadrc_demographics
#| results: asis

BRIDGE21::format_quarto("SUMMARY OF YOUR STUDY VISIT", type = "section")

BRIDGE21::format_quarto("Physician Assessment and Note", type = "subsection")

BRIDGE21::format_quarto(
  BRIDGE21::add_string(
    "Each time you are seen, we have a team of clinicians review " +
      "your cognitive assessments, questionnaires your study partner answered, and clinical information. " +
      "Below is the clinician’s feedback from your last visit. "
  ),
  type = "strwrap"
)

name <- BRIDGE21::add_string(
  "Name: " + intake$subject_fname + " " + intake$subject_lname
)
lastvisit <- BRIDGE21::add_string(
  "Last Visit: " + tail(visit$Date, 1)
)

age <- BRIDGE21::add_string("Age: " + max(visit$age_at_visit) + " Years")

subjinfo_df <- data.frame(col1 = c(name, lastvisit), col2 = c(age, ""))

flextable::flextable(subjinfo_df) %>%
  flextable::width(j = 1, width = 4) %>%
  flextable::width(j = 2, width = 2.75) %>%
  flextable::delete_part(part = "header") %>%
  flextable::border_remove() %>%
  flextable::fontsize(j = 1:2, size = 11) %>%
  flextable::add_footer_row(
    values = visit$final_impression[length(visit$final_impression)],
    colwidths = 2
  )

BRIDGE21::format_quarto(type = "newpage")

```


<!-- BOLD STUDY -->

```{r extract person information from bold study used for other parts of the report}
#| echo: false
#| eval: !expr (any(params[grepl("bold", names(params))] == TRUE))

intake <- BRIDGE21::get_database_values(
  firstname,
  lastname,
  scrn_dob,
  sex,
  data = data,
  event_name = redcap_event_name
)

intake$scrn_dob <- as.Date(
  intake$scrn_dob,
  tryFormats = c("%Y-%m-%d", "%m/%d/%y", "%m/%d/%Y")
)

date <- date_expr <- "visitdt"

visit <- BRIDGE21::get_database_values(
  data = data,
  date = date,
  event_name = redcap_event_name
)


visit$formatted_date_of_visit <- BRIDGE21::format_date(visit, visitdt)[["Date"]]

visit$age_at_visit <- floor(
  as.numeric(visit$visitdt - intake$scrn_dob) / 365.25
)

```

<!-- ABCDS STUDY -->

```{r extract the person information from the abcds study used for other parts of the report}
#| echo: false
#| eval: !expr (any(params[grepl("abcds", names(params))] == TRUE))

date <- date_expr <- "de_eval_date"

visit <- BRIDGE21::get_database_values(
  data = data,
  date = date,
  event_name = event_code
)

visit$formatted_date_of_visit <-
  BRIDGE21::format_date(visit, de_eval_date)[[
    "Date"
  ]]

```

<!-- TRCDS STUDY -->

```{r extract the person information from the trcds study used for other parts of the report}
#| echo: false
#| eval: !expr (any(params[grepl("trcds", names(params))] == TRUE))

date <- date_expr <- "examdate"

visit <- BRIDGE21::get_database_values(
  data = data,
  date = date,
  event_name = event_code
)

visit$formatted_date_of_visit <-
  BRIDGE21::format_date(visit, examdate)[[
    "Date"
  ]]

```